### ISSUE TITLE
print a string with the $ character

### ISSUE THREAD

**Issue by dragonxtek** [gpoore/text2qti#14] opened 2020-06-24 05:55 UTC
I tried to print the character $, but I guess the app thinks it's a latex instruction. I tried escape characters such as \ but it didn't work. How can I print that character?
The application enters in a while when I tried to generate the qti file.

**Comment by gpoore** [comment] 2020-06-24 14:52
This is probably a duplicate of #11, which is fixed in the dev version on GitHub. I haven't updated the version on PyPI yet.

**Comment by dragonxtek** [comment] 2020-06-24 15:53
I tried with $$ but it print the character $ twice.
Replacing $ with &#36; works fine.

**Comment by gpoore** [comment] 2020-06-24 20:26
Can you give an example of what you are dealing with? There are cases where `$` needs to be escaped as `\$` (and this is only currently supported by the version on GitHub), but those cases should be rare. It is possible that there is still a bug related to `$` processing.

**Comment by dragonxtek** [comment] 2020-07-07 21:02
I tried to print a bcrypt hash such as: $2y$12$2JkKk1Lw8OiHTxJQahd2aeJV2EU8ErnofJpL84BwZZVQHS5ngCCrm

**Comment by gpoore** [comment] 2020-07-07 22:14
I had assumed that Python-Markdown handles escapes like `\$`, but it turns out that it does not. This is fixed now in the last commit.

**Closed** 2020-07-17 15:58 UTC
Labels: bug
